// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.support.ui.Select;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
public class CreateAccountTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {e.printStackTrace();}
    driver.quit();
  }
  @Test
  public void createAccountAndBuy() {
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.id("email_create")).click();
    driver.findElement(By.id("email_create")).sendKeys("camilo.escobar.za34@gmail.com");
    driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
    try {
      Thread.sleep(4000);
    } catch (InterruptedException e) {e.printStackTrace();}
    driver.findElement(By.id("id_gender1")).click();
    driver.findElement(By.id("customer_firstname")).click();
    driver.findElement(By.id("customer_firstname")).sendKeys("Camilo");
    driver.findElement(By.id("customer_lastname")).click();
    driver.findElement(By.id("customer_lastname")).sendKeys("Escobar");
    driver.findElement(By.cssSelector(".columns-container")).click();
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("12345");
    driver.findElement(By.cssSelector(".columns-container")).click();
    driver.findElement(By.cssSelector(".account_creation:nth-child(1) > .required:nth-child(5)")).click();
    driver.findElement(By.id("passwd")).click();

    Select drpDays = new Select(driver.findElement(By.id("days")));
    drpDays.selectByValue("1");

    Select drpMonths = new Select(driver.findElement(By.id("months")));
    drpMonths.selectByValue("1");

    Select drpYears = new Select(driver.findElement(By.id("years")));
    drpYears.selectByValue("1995");

    try {
      Thread.sleep(1000);
      } catch (InterruptedException e) {e.printStackTrace();}
    
    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("lastname")).click();
    driver.findElement(By.cssSelector(".columns-container")).click();
    driver.findElement(By.cssSelector(".columns-container")).click();
    driver.findElement(By.cssSelector(".account_creation:nth-child(2) > .required:nth-child(5)")).click();
    driver.findElement(By.id("address1")).click();
    driver.findElement(By.id("address1")).sendKeys("My Address 10");
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("Santiago");
    {
      WebElement dropdown = driver.findElement(By.id("id_state"));
      dropdown.findElement(By.xpath("//option[. = 'Alabama']")).click();
    }
    driver.findElement(By.id("postcode")).click();
    driver.findElement(By.id("postcode")).sendKeys("90101");
    driver.findElement(By.cssSelector(".textarea > label")).click();
    driver.findElement(By.id("phone_mobile")).click();
    driver.findElement(By.id("phone_mobile")).sendKeys("1562973892401");
    driver.findElement(By.cssSelector("#submitAccount > span")).click();

    // Buy
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(1792, 1055));
    driver.findElement(By.cssSelector("#homefeatured > .ajax_block_product:nth-child(1) .replace-2x")).click();
    driver.findElement(By.cssSelector(".exclusive > span")).click();
    driver.manage().timeouts().implicitlyWait(2,TimeUnit.SECONDS);
    driver.findElement(By.xpath("//div[4]/a/span")).click();
    // First checkout
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.cssSelector(".button:nth-child(4) > span")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.cssSelector(".fancybox-item")).click();
    driver.findElement(By.cssSelector(".order_carrier_content")).click();
    driver.findElement(By.id("cgv")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.linkText("Pay by bank wire (order processing will be longer)")).click();
    driver.findElement(By.cssSelector("#cart_navigation span")).click();
    driver.findElement(By.cssSelector(".page-heading")).click();
    driver.close();
  }
  @Test
  public void LoginAndBuy(){
    //Login
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(1792, 1055));
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("camilo.escobar.za32@gmail.com");
    driver.findElement(By.id("passwd")).sendKeys("12345");
    driver.findElement(By.id("passwd")).sendKeys(Keys.ENTER);

    //Buy
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(1792, 1055));
    driver.findElement(By.cssSelector("#homefeatured > .ajax_block_product:nth-child(1) .replace-2x")).click();
    driver.findElement(By.cssSelector(".exclusive > span")).click();
    driver.manage().timeouts().implicitlyWait(2,TimeUnit.SECONDS);
    driver.findElement(By.xpath("//div[4]/a/span")).click();
    // First checkout
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.cssSelector(".button:nth-child(4) > span")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.cssSelector(".fancybox-item")).click();
    driver.findElement(By.cssSelector(".order_carrier_content")).click();
    driver.findElement(By.id("cgv")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.linkText("Pay by bank wire (order processing will be longer)")).click();
    driver.findElement(By.cssSelector("#cart_navigation span")).click();
    driver.findElement(By.cssSelector(".page-heading")).click();
    driver.close();
  }
}
